### PR TITLE
rewritten to ES5 build

### PR DESCRIPTION
**Pull request by SLYtiger16**
This was necessary for use with a Create-React-App to compile. An ES5 pre-compiled version.

### CODE REVIEW

**Review by prateekbh — APPROVED** [review]

**Comment by prateekbh** [comment]
can you just fix the lint errors

**Comment by SLYtiger16** [comment]
No problem

**Comment by SLYtiger16** [comment]
I am not getting any lint errors ...?

**Comment by SLYtiger16** [comment]
Now failing on a dependency of mocca 1.0.3 -> mocca-junit-reporter:
/node_modules/mocca/node_modules/mocha-junit-reporter/node_modules/strip-ansi/index.js:2
const ansiRegex = require('ansi-regex');
...using 'const' here^
not sure what you want to do, but the proposed changes work well on local projects.

**Comment by prateekbh** [comment]
yeah i'll fix this. never removed legacy tests from the forked version. LGTM

**Comment by SLYtiger16** [comment]
Cool, much appreciated. Will this push to npm?

**Comment by prateekbh** [comment]
Yep

**Comment by prateekbh** [comment]
Published 1.0.0

**Pull request merged**
